import {idleSnapshot,macVoiceId,validateRequest,type ReaderRequest,type ReaderSnapshot,type ValidatedReaderRequest} from './readerProtocol';
import {splitSpeech} from './speechSegments';
import {NativeAudioStream} from './nativeAudioStream';
import type {NativeHostResponse} from './nativeMessaging';
export class ReaderEngine {
 private state=idleSnapshot();private worker:Worker|null=null;private context:AudioContext|null=null;private meter:AudioWorkletNode|null=null;private stream:NativeAudioStream|null=null;private request:ValidatedReaderRequest|null=null;private chunks:string[]=[];private index=0;private workerReady=false;private busy=false;private paused=false;private started=false;private done=false;private epoch=0;private startingPlay=false;private finishing=false;private replayExpires=0;
 private backend:'webgpu'|'wasm'|'native'='webgpu';private nativeRequestId:string|null=null;private nativeSequence=0;private nativeChain=Promise.resolve();private timer:ReturnType<typeof setInterval>|undefined;private pauseTimer:ReturnType<typeof setTimeout>|undefined;private watchdog:ReturnType<typeof setTimeout>|undefined;private metrics:Record<string,any>={};private starvedAt:number|null=null;private waitReason='generation';
 constructor(private notify:(snapshot:ReaderSnapshot)=>void,private assetRoot:URL=new URL('./',location.href),private streamFactory=(context:AudioContext,destination:AudioNode,changed:()=>void,error:(e:unknown)=>void)=>new NativeAudioStream(context,destination,changed,error),private nativeTransport=(action:string,fields:object={})=>chrome.runtime.sendMessage({channel:'local-reader-v2',target:'background',action,...fields})){}
 get snapshot(){return{...this.state};}
 get diagnostics(){return{...this.metrics,replayExpiresAt:this.replayExpires,finishing:this.finishing,clockNow:Date.now(),modelResident:this.worker!==null,audioContextState:this.context?.state??'closed',encodedStreamResident:!!this.stream,retainedSec:this.stream?.retainedSec??0,encodedBytesProduced:this.stream?.encodedBytes??0,retainedStartSec:this.stream?.start??0,preservesPitch:this.stream?.audio.preservesPitch??null,playbackRate:this.stream?.audio.playbackRate??null,snapshot:this.snapshot};}
 private emit(patch:Partial<ReaderSnapshot>={}){this.state={...this.state,...patch};this.notify(this.snapshot);}
 private freeWorker(){clearTimeout(this.watchdog);const had=!!this.worker;this.worker?.terminate();this.worker=null;this.workerReady=false;this.busy=false;this.state.modelResident=false;if(had)this.metrics.workerReleasedMs=performance.now()-(this.metrics.requestStartedAt??performance.now());}
 stop(emit=true){this.epoch++;clearInterval(this.timer);clearTimeout(this.pauseTimer);clearTimeout(this.watchdog);this.freeWorker();const nativeRequestId=this.nativeRequestId;this.nativeRequestId=null;if(nativeRequestId)void this.nativeTransport('native-stop',{id:nativeRequestId}).catch(()=>{});this.nativeChain=Promise.resolve();this.stream?.close();this.stream=null;this.chunks=[];this.request=null;this.meter?.disconnect();this.meter=null;void this.context?.close();this.context=null;this.metrics.stopped=true;if(emit){this.state=idleSnapshot();this.notify(this.snapshot);}}
 async start(input:ReaderRequest,sessionId:string,requestedAt=Date.now()){
  this.stop(false);const request=validateRequest(input),epoch=this.epoch;this.request=request;this.backend=macVoiceId(request.voice)?'native':'webgpu';this.chunks=this.backend==='native'?[request.text]:splitSpeech(request.text);this.index=0;this.paused=false;this.started=false;this.done=false;this.finishing=false;this.startingPlay=false;this.replayExpires=0;this.starvedAt=null;this.waitReason='generation';
  this.metrics={commandRequestedAt:requestedAt,engineTimeOrigin:performance.timeOrigin,requestStartedAt:performance.now(),chunks:[],underruns:[],seeks:[],speedChanges:[],speechSource:this.backend==='native'?'mac-system-speech':'kokoro',method:this.backend==='native'?'Native helper lifecycle callbacks; no browser audio or inferred timeline.':'AudioWorklet first non-silent rendered sample; browser audible estimate, not microphone loopback.'};
  this.state={...idleSnapshot(),sessionId,voice:request.voice,voiceName:request.voiceName,speed:request.speed,phase:'preparing',totalChunks:this.chunks.length,message:this.backend==='native'?'Starting the Mac voice…':'Preparing the installed voice…',...(this.backend==='native'?{speechMode:'system' as const}:{})};this.emit();
  if(this.backend==='native'){this.speakSystem(epoch);return;}
  try{
   const context=new AudioContext({latencyHint:'playback',sampleRate:24000});this.context=context;await context.audioWorklet.addModule(new URL('audio-meter.js',this.assetRoot));if(epoch!==this.epoch){void context.close();return;}
   this.meter=new AudioWorkletNode(context,'reader-meter');this.meter.connect(context.destination);this.meter.port.onmessage=event=>{if(epoch!==this.epoch||event.data.type!=='first-rendered-sound'||this.metrics.firstRenderedSoundMs!==undefined)return;const stamp=context.getOutputTimestamp(),latency=context.outputLatency||context.baseLatency||0;const estimated=stamp.performanceTime&&stamp.contextTime?stamp.performanceTime+(event.data.contextTime-stamp.contextTime)*1000:performance.now()+latency*1000;Object.assign(this.metrics,{firstRenderedSoundMs:performance.now()-this.metrics.requestStartedAt,firstAudibleEstimateMs:estimated-this.metrics.requestStartedAt,commandToFirstRenderedMs:performance.timeOrigin+performance.now()-this.metrics.commandRequestedAt,commandToFirstAudibleEstimateMs:performance.timeOrigin+estimated-this.metrics.commandRequestedAt,browserOutputLatencySec:latency});};
   const stream=this.streamFactory(context,this.meter,()=>this.tick(epoch),error=>{if(epoch===this.epoch)this.fail(error);});this.stream=stream;await stream.open();if(epoch!==this.epoch){stream.close();return;}stream.speed(this.state.speed);if(!this.paused)await context.resume();if(epoch!==this.epoch)return;this.spawnWorker(epoch);this.timer=setInterval(()=>this.tick(epoch),250);
  }catch(e){if(epoch===this.epoch)this.fail(e);}
 }
 private spawnWorker(epoch:number){
  if(this.worker||this.done||this.paused)return;const worker=new Worker(new URL('speech-worker.js',this.assetRoot));this.worker=worker;this.emit({modelResident:true});worker.onerror=e=>{if(worker===this.worker)this.fail(Error(e.message||'The voice could not start.'));};
  worker.onmessage=event=>{if(epoch!==this.epoch||worker!==this.worker)return;void this.onWorker(event.data,worker,epoch).catch(e=>{if(epoch===this.epoch)this.fail(e);});};
  this.watchdog=setTimeout(()=>{if(worker===this.worker)this.fail(Error('The installed voice did not become ready. Close and try again.'));},90000);worker.postMessage({type:'load',backend:this.backend});
 }
 private async onWorker(data:any,worker:Worker,epoch:number){
  if(data.type==='fallback'&&this.backend==='webgpu'){this.metrics.gpuUnavailable=data.reason;this.freeWorker();this.backend='wasm';this.emit({phase:'preparing',message:'Using the installed CPU voice. Preparation may take longer.'});this.spawnWorker(epoch);return;}
  if(data.type==='error')throw Error(data.error);
  if(data.type==='ready'){clearTimeout(this.watchdog);this.workerReady=true;Object.assign(this.metrics,{backend:data.backend,threads:data.threads,crossOriginIsolated:data.crossOriginIsolated});this.metrics.modelReadyMs??=performance.now()-this.metrics.requestStartedAt;this.emit({phase:this.paused?'paused':this.started?'playing':'buffering',message:'Preparing audio ahead…'});this.pump();}
  else if(data.type==='split'&&data.index===this.index){if(!Array.isArray(data.parts)||data.parts.join('')!==this.chunks[this.index]||data.parts.some((s:string)=>!s.length))throw Error('Invalid speech split.');clearTimeout(this.watchdog);this.busy=false;this.chunks.splice(this.index,1,...data.parts);this.metrics.tokenSplits=(this.metrics.tokenSplits??0)+1;this.emit({totalChunks:this.chunks.length});this.pump();}
  else if(data.type==='audio'&&data.index===this.index&&this.stream){
   clearTimeout(this.watchdog);const samples=data.samples as Float32Array;if(!samples.length||samples.some(x=>!Number.isFinite(x)))throw Error('The voice returned invalid audio.');
   const stream=this.stream;this.index++;this.metrics.firstPcmMs??=performance.now()-this.metrics.requestStartedAt;this.metrics.chunks.push({index:data.index,chars:this.chunks[data.index].length,audioSec:samples.length/data.sampleRate,generationMs:data.generationMs,padding:data.padding,arrivedMs:performance.now()-this.metrics.requestStartedAt});
   await stream.append(samples,data.sampleRate);if(epoch!==this.epoch||stream!==this.stream)return;
   this.busy=false;if(this.index===this.chunks.length){this.done=true;this.freeWorker();await stream.finish();if(epoch!==this.epoch)return;}
   this.tick(epoch);this.pump();
  }
 }
 handleNativeMessage(message:NativeHostResponse){
  const epoch=this.epoch;this.nativeChain=this.nativeChain.then(()=>this.onNativeMessage(message,epoch)).catch(error=>{if(epoch===this.epoch)this.fail(error);});
 }
 private async onNativeMessage(message:NativeHostResponse,epoch:number){
  if(this.backend!=='native'||epoch!==this.epoch||message.id!==this.nativeRequestId)return;
  clearTimeout(this.watchdog);
  if(message.type==='error')throw Error(message.message||'The selected Mac voice is unavailable. Choose another voice or use Kokoro.');
  if(message.type==='started'){this.started=true;this.metrics.systemSpeechStartedMs=performance.now()-this.metrics.requestStartedAt;this.emit({phase:'playing',message:undefined,modelResident:false});return;}
  if(message.type==='ended'){this.nativeRequestId=null;this.done=true;this.metrics.completeMs=performance.now()-this.metrics.requestStartedAt;this.emit({phase:'complete',message:'Finished. Replay starts from the beginning.',modelResident:false,generatedChunks:1});return;}
  if(message.type==='cancelled'){this.nativeRequestId=null;this.done=true;this.emit({phase:'complete',message:'Stopped. Replay starts from the beginning.',modelResident:false});}
 }
 private speakSystem(epoch:number){
  if(this.backend!=='native'||!this.request||epoch!==this.epoch)return;
  const id=`${this.state.sessionId}:${epoch}:${++this.nativeSequence}`;this.nativeRequestId=id;this.done=false;this.started=false;
  this.emit({phase:'preparing',message:'Starting the Mac voice…',speechMode:'system',elapsedSec:0,durationSec:null,bufferedSec:0,seekableStartSec:undefined,seekableEndSec:undefined});
  this.watchdog=setTimeout(()=>{if(id===this.nativeRequestId)this.fail(Error('The Mac voice did not start. Close and try again.'));},15000);
  void this.nativeTransport('native-speak',{id,text:this.request.text}).then(result=>{if(result?.error&&id===this.nativeRequestId)this.fail(Error(result.error));}).catch(error=>{if(id===this.nativeRequestId)this.fail(error);});
 }
 private pump(){
  const speed=this.state.speed;if(this.paused||this.done||this.busy||!this.workerReady||!this.request||!this.stream||this.stream.ahead/speed>22)return;this.busy=true;this.watchdog=setTimeout(()=>this.fail(Error('Speech generation stopped responding. Close and try again.')),120000);
  if(!this.worker){this.busy=false;return;}this.worker.postMessage({type:'generate',index:this.index,text:this.chunks[this.index],voice:this.request.voice,speed:1});
 }
 private tick(epoch:number){
  const stream=this.stream;if(epoch!==this.epoch||!stream||!this.context)return;
  const end=stream.end,start=stream.start,position=stream.position,ahead=stream.ahead,speed=this.state.speed;
  this.emit({elapsedSec:position,durationSec:this.done?end:null,bufferedSec:ahead,seekableStartSec:start,seekableEndSec:end,generatedChunks:this.index,modelResident:!!this.worker,replayExpiresAt:this.replayExpires||undefined});
  if(this.done&&stream.ended&&!this.finishing){this.finishing=true;this.replayExpires=Date.now()+120000;this.metrics.completeMs=performance.now()-this.metrics.requestStartedAt;void this.context.suspend();this.emit({phase:'complete',message:'Finished. Available audio is kept for two minutes for replay; Close clears it now.',modelResident:false,replayExpiresAt:this.replayExpires});}
  if(this.finishing){if(Date.now()>=this.replayExpires){const final={...this.state,phase:'complete' as const,seekableStartSec:0,seekableEndSec:0,bufferedSec:0,replayExpiresAt:undefined,message:'Replay audio released. Start a new reading to listen again.'};this.stop(false);this.state=final;this.notify(this.snapshot);}return;}
  if(!this.paused&&!this.startingPlay&&end>0&&((!this.started&&(this.done||ahead/speed>=(this.backend==='wasm'?12:4)))||(this.started&&stream.audio.paused))){this.startingPlay=true;void stream.play().then(()=>{if(epoch!==this.epoch)return;this.startingPlay=false;if(!this.paused){this.started=true;this.emit({phase:stream.ahead>.03?'playing':'buffering',message:undefined});}}).catch(e=>{if(epoch===this.epoch){this.startingPlay=false;this.fail(e);}});}
  if(!this.paused&&this.started){if(ahead<.03&&!this.done){this.starvedAt??=performance.now();this.emit({phase:'buffering',message:'At the available audio edge. Reading continues when more is ready.'});}else if(ahead>.1){if(this.starvedAt!==null){(this.waitReason==='seek'?(this.metrics.seekWaits??=[]):this.metrics.underruns).push({gapSec:(performance.now()-this.starvedAt)/1000,atAudioSec:position});this.waitReason='generation';this.starvedAt=null;}this.emit({phase:'playing',message:undefined});}}
  void stream.evict().catch(e=>{if(epoch===this.epoch)this.fail(e);});this.pump();
 }
 async pause(){if(this.backend==='native'){if(!this.nativeRequestId)return;const id=this.nativeRequestId;clearTimeout(this.watchdog);this.nativeRequestId=null;await this.nativeTransport('native-stop',{id}).then(result=>{if(result?.error)throw Error(result.error);});this.done=true;this.emit({phase:'complete',message:'Stopped. Replay starts from the beginning.',modelResident:false});return;}if(!this.context||!this.stream||['idle','error'].includes(this.state.phase))return;this.paused=true;this.stream.pause();await this.context.suspend();if(this.done){this.finishing=true;this.replayExpires=Date.now()+120000;}this.emit({phase:'paused',message:undefined,replayExpiresAt:this.replayExpires||undefined});clearTimeout(this.pauseTimer);this.pauseTimer=setTimeout(()=>{if(this.paused){this.freeWorker();this.emit({modelResident:false,message:'Paused · voice memory released. Available audio is retained.'});}},30000);}
 async resume(){if(this.backend==='native'){if(this.request&&['complete'].includes(this.state.phase))this.speakSystem(this.epoch);return;}if(!this.context||!this.stream)return;clearTimeout(this.pauseTimer);this.finishing=false;this.replayExpires=0;this.paused=false;await this.context.resume();if(this.stream.ended)this.stream.seek(this.stream.start);if(this.started)await this.stream.play();if(!this.worker&&!this.done)this.spawnWorker(this.epoch);this.emit({phase:this.started?'playing':'buffering',message:undefined,replayExpiresAt:undefined});this.tick(this.epoch);this.pump();}
 seek(seconds:number){if(this.backend==='native')return; if(!this.stream)return;const from=this.stream.position;this.waitReason=seconds>=this.stream.end-.05?'seek':'generation';this.stream.seek(seconds);this.metrics.seeks.push({from,to:this.stream.position,requested:seconds});if(this.finishing||this.done&&this.paused){this.finishing=true;this.replayExpires=Date.now()+120000;this.paused=true;this.emit({phase:'paused',message:undefined,replayExpiresAt:this.replayExpires});}this.tick(this.epoch);}
 setSpeed(speed:number){if(this.backend==='native')return;if(!Number.isFinite(speed)||speed<.5||speed>2)throw Error('Choose a speed from 0.5× to 2×.');this.stream?.speed(speed);this.metrics.speedChanges.push({from:this.state.speed,to:speed,at:this.stream?.position??0});this.emit({speed});this.tick(this.epoch);}
 private fail(error:unknown){const final={...this.state,phase:'error' as const,error:error instanceof Error?error.message:String(error),modelResident:false,seekableStartSec:0,seekableEndSec:0};this.metrics.failure=final.error;this.stop(false);this.state=final;this.notify(this.snapshot);}
}
